name: Generate images Readme

on:
  schedule: # Run every day
    - cron: "0 */24 * * *" 

  workflow_dispatch: # Allows to manually run the job at any time

jobs:
  generate:
    name: Generate snake animation
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Generates a snake game from a user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # The content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file>
      - name: push snake animation to the branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Generate stats for github
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: ${{ github.repository_owner }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



# CREDITS:
# Snake - https://github.com/Platane/Platane/blob/master/.github/workflows/main.yml#L24-L29
# Statistics - https://github.com/vn7n24fzkq/github-profile-summary-cards
