name: generate animation

on:
  schedule: # run every 24 hours
    - cron: "0 */24 * * *" 

  workflow_dispatch: # allows to manually run the job at any time

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: assets/github-contribution-grid-snake.svg

      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push snake animation to the branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



# CREDITS:
# https://github.com/Platane/Platane/blob/master/.github/workflows/main.yml#L24-L29
